name: sync-notion-to-github

on:
  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: notion-sync
      uses: YouXam/Notion-GitHub-Sync@v1
      with:
        notion_token: ${{ secrets.NOTION_TOKEN }}
